version: "3.9"

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8001:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=wordpress
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: ./wordpress
    volumes:
      - /run/media/souptik/Data/wordpress-data-backup:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  wordpress_db_data: {}